/**
 * api/card.js — Vercel Serverless Function: vCard Contact Download Endpoint.
 *
 * This is the OPTIONAL server-side counterpart to the local-first vCard
 * generated by src/utils/vcard.ts. It serves two purposes:
 *
 *   1. TRACKED SHARING: Each request increments a CountAPI counter, letting
 *      the app display a live "total scans" number on Dashboard and Stats.
 *
 *   2. URL-BASED SHARING: Returns a text/vcard response that triggers the
 *      phone's native "Add Contact" screen — useful when you want a stable
 *      URL (e.g. on a physical printed card) rather than an embedded vCard.
 *
 * Profile data is read from config/profile.js (a static file in the repo).
 * This does NOT read from AsyncStorage — server-side and client-side profile
 * data are intentionally separate for this single-user MVP.
 *
 * Route: GET /api/card
 * Content-Type: text/vcard; charset=utf-8
 * CORS: Enabled (Access-Control-Allow-Origin: *)
 */
export default async function handler(req, res) {
  try {
    await fetch('https://api.countapi.xyz/hit/tapshare-thabo/scans');
  } catch (e) {
    console.error('Counter ping failed', e);
  }

  const profile = require('../config/profile.js');

  const vcard = [
    'BEGIN:VCARD',
    'VERSION:3.0',
    `N:${profile.lastName};${profile.firstName};;;`,
    `FN:${profile.firstName} ${profile.lastName}`,
    `TEL;TYPE=CELL:${profile.phone}`,
    `EMAIL:${profile.email}`,
    ...profile.links.map(l => `URL:${l.url}`),
    'END:VCARD',
  ].join('\r\n');

  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.setHeader('Content-Type', 'text/vcard; charset=utf-8');
  res.setHeader('Content-Disposition', `inline; filename="${profile.firstName}-${profile.lastName}.vcf"`);
  res.status(200).send(vcard);
}
